services:
  - type: web
    name: django-docker-app
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
